services:

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
      MYSQL_DATABASE: dekku
    networks:
      - local

  redis:
    image: redis:latest
    container_name: redis
    # restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./infra/redis/data/:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - local

  es:
    build:
      context: dockerfile/es
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - local

networks:
  local:
    driver: bridge