version: '3.8'

services:
  # app = 서버 컨테이너를 별도로 생성
#  app:
#    container_name: dekku
#    image: openjdk:17
#    ports:
#      - "8080:8080"
#    networks:
#      - dekku-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: dekku1234
      MARIADB_DATABASE: dekku
      MARIADB_USER: dekku
      MARIADB_PASSWORD: dekku1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dekku-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-bridge

volumes:
  mariadb_data:

networks:
  dekku-network:
    driver: bridge