services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: dekku1234
      MARIADB_DATABASE: dekku
      MARIADB_USER: dekku
      MARIADB_PASSWORD: dekku1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dekku-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - dekku-network

volumes:
  mariadb_data:
  redis_data:

networks:
  dekku-network:
    driver: bridge