import "./globals.css";
import localFont from "next/font/local";
import Header from "./components/Header";

// Pretendard Font load
const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr" className={`${pretendard.variable} font-pretendard`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
