export const datas = [
  {
    id: 1,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "한국최고ILoveKorea",
    introduce: "한국 전통과 현대를 사랑하는 데스크 디자이너입니다.",
    title: "한국풍 데스크셋업의 매력",
    content: "역시 데스크테리어는 한국풍이지~ 이 데스크셋업은 한국 전통 스타일과 현대적인 감각이 절묘하게 어우러져 있습니다.",
    views: "21,000",
    likes: "4,200",
    comments: "140",
    createdAt: "2024-06-01",
    style: "modern",
    color: "black_white",
    job: "designer"
  },
  {
    id: 2,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "게임밥잠",
    introduce: "게임을 사랑하는 열정적인 게이머입니다.",
    title: "게임을 위한 최고의 데스크",
    content: "같이 게임하실 분 연락주세요! 이 데스크는 게임을 위한 최적의 환경을 제공합니다. 화려한 조명과 편안한 의자가 특징입니다.",
    views: "8,000",
    likes: "2,000",
    comments: "90",
    createdAt: "2024-06-08",
    style: "gamer",
    color: "black",
    job: "gamer"
  },
  {
    id: 3,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "_nice_guy123",
    introduce: "조용하고 편안한 공간을 추구하는 사람입니다.",
    title: "혼자만의 평화로운 공간",
    content: "혼자 있고 싶어요 다 나가주세요. 이 공간은 조용하고 편안한 분위기를 자아내며, 혼자서의 작업에 적합합니다.",
    views: "12,000",
    likes: "1,500",
    comments: "105",
    createdAt: "2024-06-15",
    style: "minimal",
    color: "white",
    job: "freelancer"
  },
  {
    id: 4,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "CoolDeskFan",
    introduce: "최신 데스크 가구에 열광하는 데스크 애호가입니다.",
    title: "최신 데스크 가구 리뷰",
    content: "새로운 데스크 가구 너무 좋아요! 최신 디자인의 데스크 가구로 꾸며진 공간으로, 기능성과 미학을 동시에 만족시킵니다.",
    views: "15,000",
    likes: "3,800",
    comments: "125",
    createdAt: "2024-06-22",
    style: "modern",
    color: "gray",
    job: "designer"
  },
  {
    id: 5,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "TechEnthusiast",
    introduce: "기술 혁신을 사랑하는 데스크 설계자입니다.",
    title: "최신 기술이 접목된 데스크",
    content: "최신 기술로 꾸민 제 데스크! 최신 기술과 혁신적인 가구 디자인을 접목하여 작업 효율을 높였습니다.",
    views: "17,000",
    likes: "5,000",
    comments: "155",
    createdAt: "2024-07-17",
    style: "gamer",
    color: "black",
    job: "developer"
  },
  {
    id: 6,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "MinimalistMaster",
    introduce: "미니멀리즘의 가치를 중요시하는 디자이너입니다.",
    title: "미니멀리즘의 정수",
    content: "미니멀한 디자인이 최고입니다. 군더더기 없는 깔끔한 디자인으로, 시각적 평화를 제공합니다.",
    views: "10,000",
    likes: "2,200",
    comments: "95",
    createdAt: "2024-07-18",
    style: "minimal",
    color: "white",
    job: "designer"
  },
  {
    id: 7,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "GamerPro",
    introduce: "게임을 위한 최적의 데스크셋업을 연구하는 게이머입니다.",
    title: "게임을 위한 완벽한 셋업",
    content: "게임할 때 이 데스크가 최고! 모든 게이머를 위해 설계된 최적의 데스크셋업입니다. 대형 모니터와 편안한 의자가 특징입니다.",
    views: "14,000",
    likes: "3,600",
    comments: "110",
    createdAt: "2024-07-19",
    style: "gamer",
    color: "black",
    job: "gamer"
  },
  {
    id: 8,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "Workaholic",
    introduce: "업무 효율성을 높이기 위해 노력하는 사람입니다.",
    title: "효율적인 작업 환경",
    content: "효율적인 작업 환경을 위한 데스크. 업무에 집중할 수 있도록 설계된 기능적이고 세련된 데스크입니다.",
    views: "13,000",
    likes: "2,800",
    comments: "85",
    createdAt: "2024-07-20",
    style: "modern",
    color: "gray",
    job: "office_worker"
  },
  {
    id: 9,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "CreativeSoul",
    introduce: "창의적 작업을 위한 공간을 설계하는 창의적인 사람입니다.",
    title: "창의력 자극하는 공간",
    content: "창의력을 자극하는 데스크. 창의적 작업을 위한 환경으로, 다양한 색상과 디자인 요소가 돋보입니다.",
    views: "18,000",
    likes: "4,300",
    comments: "130",
    createdAt: "2024-07-21",
    style: "creative",
    color: "blue",
    job: "designer"
  },
  {
    id: 10,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "DeskLover",
    introduce: "편안한 데스크 환경을 선호하는 사람입니다.",
    title: "편안한 데스크 환경",
    content: "편안한 데스크가 필요하신가요? 편안함을 최우선으로 고려한 데스크셋업으로, 오랜 시간 작업에도 부담이 없습니다.",
    views: "20,000",
    likes: "4,500",
    comments: "150",
    createdAt: "2024-07-22",
    style: "modern",
    color: "black_white",
    job: "freelancer"
  },
  {
    id: 11,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "OfficeGuru",
    introduce: "전문적인 오피스 환경을 설계하는 전문가입니다.",
    title: "완벽한 오피스 환경",
    content: "완벽한 오피스 환경. 전문적인 업무를 위한 데스크셋업으로, 모든 요구를 충족시킵니다.",
    views: "19,000",
    likes: "4,800",
    comments: "115",
    createdAt: "2024-07-24",
    style: "modern",
    color: "gray",
    job: "office_worker"
  },
  {
    id: 12,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "HomeHacker",
    introduce: "편안한 홈 오피스를 꾸미는 것을 즐기는 사람입니다.",
    title: "편안한 홈 오피스",
    content: "편안한 홈 오피스. 집에서도 전문적인 작업 환경을 제공하는 데스크셋업입니다.",
    views: "17,500",
    likes: "4,300",
    comments: "120",
    createdAt: "2024-07-25",
    style: "minimal",
    color: "white",
    job: "homemaker"
  },
  {
    id: 13,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "DigitalNomad",
    introduce: "이동 중에도 효율적인 작업 환경을 추구하는 사람입니다.",
    title: "이동 중에도 효율적인 작업 환경",
    content: "이동 중에도 효율적인 작업 환경. 언제 어디서나 최상의 작업 환경을 제공하는 데스크셋업입니다.",
    views: "22,000",
    likes: "5,200",
    comments: "160",
    createdAt: "2024-07-26",
    style: "modern",
    color: "black",
    job: "freelancer"
  },
  {
    id: 14,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "TechJunkie",
    introduce: "최신 기기를 활용한 데스크셋업에 관심이 많은 사람입니다.",
    title: "최신 기기와 함께하는 데스크",
    content: "최신 기기와 함께. 최신 기술이 접목된 데스크셋업으로, 모든 기술적 요구를 만족시킵니다.",
    views: "19,000",
    likes: "4,600",
    comments: "110",
    createdAt: "2024-07-27",
    style: "gamer",
    color: "black",
    job: "developer"
  },
  {
    id: 15,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "StudyMaster",
    introduce: "학습과 집중력을 높이기 위해 노력하는 사람입니다.",
    title: "공부하기 좋은 데스크셋업",
    content: "공부하기 좋은 환경. 집중력을 높이기 위한 데스크셋업으로, 최적의 학습 환경을 제공합니다.",
    views: "15,500",
    likes: "3,800",
    comments: "100",
    createdAt: "2024-07-28",
    style: "study",
    color: "blue",
    job: "student"
  },
  {
    id: 16,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "ZenSpace",
    introduce: "편안하고 조용한 공간을 선호하는 사람입니다.",
    title: "편안하고 조용한 공간",
    content: "편안하고 조용한 공간. 스트레스 없이 작업할 수 있는 조용한 데스크셋업입니다.",
    views: "16,500",
    likes: "4,100",
    comments: "120",
    createdAt: "2024-07-29",
    style: "minimal",
    color: "white",
    job: "freelancer"
  },
  {
    id: 17,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "CreativeMind",
    introduce: "창의적 사고와 디자인을 중요시하는 사람입니다.",
    title: "창의력을 자극하는 공간",
    content: "창의력을 자극하는 공간. 창의적 사고를 돕는 다양한 요소가 포함된 데스크셋업입니다.",
    views: "23,000",
    likes: "5,500",
    comments: "135",
    createdAt: "2024-07-30",
    style: "creative",
    color: "pink",
    job: "designer"
  },
  {
    id: 18,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "Minimalist",
    introduce: "미니멀 디자인의 원칙을 따르는 사람입니다.",
    title: "미니멀 디자인의 정수",
    content: "미니멀 디자인의 정수. 간결하고 세련된 디자인으로, 정신적 휴식을 제공합니다.",
    views: "14,500",
    likes: "3,600",
    comments: "95",
    createdAt: "2024-07-31",
    style: "minimal",
    color: "gray",
    job: "designer"
  },
  {
    id: 19,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "WorkspaceWizard",
    introduce: "효율적인 작업 공간을 설계하는 전문가입니다.",
    title: "효율적인 작업 공간",
    content: "효율적인 작업 공간. 최고의 작업 효율을 제공하는 데스크셋업입니다. 모든 것이 손쉽게 접근 가능합니다.",
    views: "20,500",
    likes: "4,900",
    comments: "125",
    createdAt: "2024-08-01",
    color: "black_white",
    job: "office_worker"
  },
  {
    id: 20,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "GamerZone",
    introduce: "게임을 즐기는 공간 설계를 전문으로 하는 사람입니다.",
    title: "최고의 게임 환경",
    content: "최고의 게임 환경. 게임을 위해 설계된 데스크셋업으로, 모든 게이머의 꿈을 실현합니다.",
    views: "26,000",
    likes: "6,500",
    comments: "170",
    createdAt: "2024-08-02",
    style: "gamer",
    color: "black",
    job: "gamer"
  },
  {
    id: 21,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "TechFanatic",
    introduce: "최신 기술과 디자인에 열광하는 사람입니다.",
    title: "최신 기술로 꾸민 데스크",
    content: "최신 기술로 꾸민 데스크. 최신 기술과 혁신적인 디자인이 접목된 작업 공간입니다.",
    views: "25,000",
    likes: "6,000",
    comments: "160",
    createdAt: "2024-08-03",
    style: "modern",
    color: "blue",
    job: "developer"
  },
  {
    id: 22,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "DeskEnthusiast",
    introduce: "작업 효율성을 높이는 데스크에 관심이 많은 사람입니다.",
    title: "작업 효율을 높이는 데스크",
    content: "작업 효율을 높이는 데스크. 다양한 기능이 포함된 데스크셋업으로, 생산성을 극대화합니다.",
    views: "18,500",
    likes: "4,700",
    comments: "120",
    createdAt: "2024-08-04",
    style: "modern",
    color: "gray",
    job: "developer"
  },
  {
    id: 23,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "StylishWork",
    introduce: "스타일리시한 작업 환경을 추구하는 사람입니다.",
    title: "스타일리시한 작업 환경",
    content: "스타일리시한 작업 환경. 세련된 디자인으로 작업의 질을 높여주는 데스크셋업입니다.",
    views: "22,500",
    likes: "5,300",
    comments: "130",
    createdAt: "2024-08-05",
    style: "lovely",
    color: "pink",
    job: "designer"
  },
  {
    id: 24,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "ProductiveSpace",
    introduce: "생산성 향상을 위한 데스크 설계를 전문으로 하는 사람입니다.",
    title: "생산성을 높이는 데스크",
    content: "생산성을 높이는 데스크. 효율적인 작업을 위한 최적의 환경을 제공합니다.",
    views: "19,000",
    likes: "4,400",
    comments: "110",
    createdAt: "2024-08-06",
    style: "modern",
    color: "gray",
    job: "developer"
  },
  {
    id: 25,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "ModernMinimal",
    introduce: "모던하고 미니멀한 디자인을 선호하는 사람입니다.",
    title: "모던하고 미니멀한 공간",
    content: "모던하고 미니멀한 공간. 현대적인 디자인과 간결한 미니멀리즘이 돋보이는 데스크셋업입니다.",
    views: "16,000",
    likes: "4,000",
    comments: "105",
    createdAt: "2024-08-07",
    style: "minimal",
    color: "white",
    job: "designer"
  },
  {
    id: 26,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "OfficeHero",
    introduce: "업무 효율을 극대화하는 오피스 환경을 설계합니다.",
    title: "최고의 오피스 환경",
    content: "최고의 오피스 환경. 업무의 효율성을 극대화할 수 있는 최고의 데스크셋업입니다.",
    views: "23,500",
    likes: "5,800",
    comments: "145",
    createdAt: "2024-08-08",
    style: "modern",
    color: "gray",
    job: "developer"
  },
  {
    id: 27,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "ChicWorkspace",
    introduce: "세련된 작업 공간을 설계하는 것을 좋아하는 사람입니다.",
    title: "세련된 작업 공간",
    content: "세련된 작업 공간. 우아한 디자인과 기능성을 갖춘 데스크셋업으로, 작업의 질을 향상시킵니다.",
    views: "20,000",
    likes: "4,900",
    comments: "125",
    createdAt: "2024-08-09",
    style: "lovely",
    color: "blue",
    job: "developer"
  },
  {
    id: 28,
    imgSrc: "/desk1.jpg",
    profileImg: "/profile_icon1.png",
    username: "UltimateDesk",
    introduce: "최고의 데스크 환경을 추구하는 사람입니다.",
    title: "궁극의 데스크 환경",
    content: "궁극의 데스크 환경. 모든 필요를 충족시키는 최상의 데스크셋업으로, 작업의 완성도를 높입니다.",
    views: "24,000",
    likes: "6,200",
    comments: "155",
    createdAt: "2024-08-10",
    style: "modern",
    color: "black_white",
    job: "freelancer"
  },
  {
    id: 29,
    imgSrc: "/desk2.jpg",
    profileImg: "/profile_icon2.png",
    username: "집사냥이",
    introduce: "게임을 위한 완벽한 공간 설계에 열정적인 사람입니다.",
    title: "게임을 위한 완벽한 공간",
    content: "게임을 위한 완벽한 공간. 게임을 즐기기 위한 모든 요소가 포함된 데스크셋업입니다.",
    views: "27,000",
    likes: "6,500",
    comments: "170",
    createdAt: "2024-08-11",
    style: "gamer",
    color: "black",
    job: "gamer"
  },
  {
    id: 30,
    imgSrc: "/desk3.jpg",
    profileImg: "/profile_icon3.png",
    username: "CreativeHub",
    introduce: "창의적인 작업 환경을 설계하는 것을 좋아하는 사람입니다.",
    title: "창의적인 작업을 위한 공간",
    content: "창의적인 작업을 위한 공간. 다양한 창의적 작업을 지원하는 데스크셋업입니다.",
    views: "24,500",
    likes: "6,800",
    comments: "180",
    createdAt: "2024-08-12",
    style: "creative",
    color: "blue",
    job: "designer"
  }
];
